{
    'name': 'SmartFinance AI',
    'version': '1.0.0',
    'summary': 'AI-powered financial insights and alerts',
    'author': 'The Odoo-Crewz',
    'category': 'Accounting/Finance',
    'depends': [
        'base',
        'account',
        'hr',
        'hr_expense',
        'crm',
        'project',
        'purchase',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/insight_views.xml',
        'views/dashboard_views.xml',
        'views/chat_views.xml',
        'views/kpi_dashboard_views.xml',
        'views/report_views.xml',
        'views/menu_views.xml',
        'data/cron_jobs.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}